### ISSUE TITLE
Improve error message when unable to resolve

### ISSUE THREAD

**Issue by bocca** [koenbeuk/EntityFrameworkCore.Projectables#26]
Some expressions throw an error with message "Unable to resolve generated expression". It would be nice to improve that message with the offending class.member and some hint of the cause (maybe the inner exception if there is any).

**Comment by koenbeuk** [comment]
Good idea! "Unable to resolve generated expression" typically means that there was an issue during source generation, this tends to often be a bug in this library rather than a user error. Nonetheless it happens often enough that a more detailed exception message has merit, Feel free to submit a PR, otherwise I can look into this later.

**Comment by koenbeuk** [comment]
Currently, the exception carries a data property: `GeneratedContainingTypeName` which can be used to identify the method that was failing. this reveals both the Class and Member for which it tried to resolve an Expression. Still, the exception message itself could be improved

**Comment by koenbeuk** [comment]
Fixed with #28
