### ISSUE TITLE
Support for "is" operator, for TPT models

### ISSUE THREAD

**Issue by PhenX** [koenbeuk/EntityFrameworkCore.Projectables#35]
Hello, first, thank you for this library which helps us keep our code mode clean !

I'm currently struggling using the "is" operator which is supported by EF core with Table Per Type classes, for example : 

  [Projectable]
  public bool IsTelecom => this is Telecom;

All it seems to do is make invalid C# code in the source generator

I'd like to contribute with a pull request but I don't know where to begin.

I found something that could maybe help, about the is operator in expression trees, related to the OfType Linq method : https://stackoverflow.com/a/57949043/92315

**Comment by koenbeuk** [comment]
The problem with the IS operator seems to be related to how expressions are rewritten, the following gets rewritten from:

```csharp
class Test { 
      [Projectable] public bool Foo => this is Test; // Works in EF and always yields true
}
```

as 

```csharp
class Generated_Test { 
     public static System.Linq.Expressions.Expression<System.Func<global::Test, bool>> Expression()
        {
            return (global::Test @this) => 
                @thisis global::Test;
        }
    }
}
```

note how `@this` and `is` are 'tied' together. This is causing compilation issues. Certainly a bug. Happy to receive a PR for this of course!

**Comment by PhenX** [comment]
Thank you for your quick answer, is this generated code made by your library or do you use something built-in to generate the different expression parts ? Either way, could you show me where in the code this happens so that I can take a look ?
Also, do you recommend a way to debug the code generator, I know it's not trivial, because it happens on compilation, I'd like to know how you proceed.

**Comment by koenbeuk** [comment]
Thanks for wanting to take a look at this. 

First, we can create a new unit test that uses [VerifyTest](https://github.com/VerifyTests/Verify) to verify the generated code here: https://github.com/koenbeuk/EntityFrameworkCore.Projectables/blob/master/tests/EntityFrameworkCore.Projectables.Generator.Tests/ProjectionExpressionGeneratorTests.cs 

Afterwards the issue is most likely related to how we rewrite the expression tree which happens over here: https://github.com/koenbeuk/EntityFrameworkCore.Projectables/blob/master/src/EntityFrameworkCore.Projectables.Generator/ExpressionSyntaxRewriter.cs

I'm happy to take a swing at this later this week but feel free to beat me to it! 

(I also suspect that the `as` operator suffers from the same issue, perhaps we should also include a test for that).

**Comment by koenbeuk** [comment]
Thanks!

**Comment by koenbeuk** [comment]
https://www.nuget.org/packages/EntityFrameworkCore.Projectables/2.3.01-beta.1

**Comment by PhenX** [comment]
Thank you! It works great for our use case :)
