### ISSUE TITLE
NullConditionalRewriteSupport generates uncompilable source when used with the ?? Operator

### ISSUE THREAD

**Issue by jhartmann123** [koenbeuk/EntityFrameworkCore.Projectables#48]
Based on [this repro](https://github.com/koenbeuk/EntityFrameworkCore.Projectables/files/9939569/Projectables.Coverage.zip) from https://github.com/koenbeuk/EntityFrameworkCore.Projectables/issues/47, the following expression is used:

`SomeNumber = fancyClass != null ? fancyClass.FancyNumber : 3`

When merged into a conditional expression, we get
`SomeNumber = fancyClass?.FancyNumber ?? 3`

Now EFP0002 tells me to enable the NullConditionalRewriteSupport. Once I do that, I get
`CS0019	Operator '??' cannot be applied to operands of type '<null>' and 'int'`
Generated source:
`SomeNumber = fancyClass != null ? (fancyClass.FancyNumber ) : null?? 3`

Adding additional braces doesn't help
`SomeNumber = (fancyClass?.FancyNumber) ?? 3`
Results in
`CS0173	Type of conditional expression cannot be determined because there is no implicit conversion between 'int' and '<null>'	`
Generated source:
`SomeNumber = (fancyClass != null ? (fancyClass.FancyNumber) : null) ?? 3`

# Expected result
`SomeNumber = fancyClass != null ? fancyClass.FancyNumber : 3`

**Comment by koenbeuk** [comment]
Thanks for reporting this. I'll look into fixing this. Please note that you will likely want to use `NullConditionalRewriteSupport.Ignore` instead of `NullConditionalRewriteSupport.Rewrite` as EF Core handles nullability for you for most database providers. 

`Ignore` will result in the following generated source: `fancyClass.FancyNumber ?? 3`
